# Tópicos de Inteligencia Artificial
## Tarea 3
### Gabriel Briones Sayeg A01222517

1. Considera la siguiente tabla de datos numéricos:

| x1    | x2   | y |
|-------|------|---|
| 0.15  | 3500 | 8 |
| -0.1  | 3400 | 5 |
| 0     | 4000 | 3 |
| -0.25 | 3900 | 1 |
| 0.05  | 3200 | 7 |

a) Escalar la variable x1 mediante la fórmula (xk1 − 𝑥̅)/Rango, donde 𝑥̅ y 𝑅𝑎𝑛𝑔𝑜 son el promedio y Rango de la variable x1.

b) Escalar la variable x2 mediante la fórmula (xk2 − 𝑥̅)/s, donde 𝑠 es la desviación estándar de x2.

c) Escalar la variable y entre −10 y 20.


In [1]:
import math

import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    "x1": [0.15, -0.1, 0, -0.25, 0.05],
    "x2": [3500, 3400, 4000, 3900, 3200],
    "y": [8, 5, 3, 1, 7]
})
print(df)

     x1    x2  y
0  0.15  3500  8
1 -0.10  3400  5
2  0.00  4000  3
3 -0.25  3900  1
4  0.05  3200  7


In [3]:
def minmax_normalization(array, a=0, b=1):
    result = []
    _min = min(array)
    _max = max(array)
    _range = _max - _min
    for element in array:
        result.append(a + ((element - _min) * (b - a))/_range)
    return result

def mean_normalization(array):
    result = []
    _range = max(array) - min(array)
    _average = np.average(array)
    for element in array:
        result.append((element - _average)/_range)
    return result

def standarization(array):
    result = []
    std = np.std(array)
    _average = np.average(array)
    for element in array:
        result.append((element - _average)/std)
    return result
    

print("X1 scaled: ", mean_normalization(df["x1"]))
print("X2 scaled: ", standarization(df["x2"]))
print("Y scaled: ", minmax_normalization(df["y"], -10, 20))

X1 scaled:  [0.44999999999999996, -0.17500000000000002, 0.07500000000000001, -0.5499999999999999, 0.20000000000000004]
X2 scaled:  [-0.3296902366978935, -0.659380473395787, 1.318760946791574, 0.9890707100936804, -1.318760946791574]
Y scaled:  [20.0, 7.142857142857142, -1.4285714285714288, -10.0, 15.714285714285715]


2. Existen varias formas de medir la distancia entre puntos. Más adelante requeriremos algunas de ellas para algunos algoritmos de clasificación. Por el momento investiga cómo se definen las distancias o métricas indicadas en cada inciso y utilízalas para encontrar la distancia entre los puntos 𝐴=(2,1) y 𝐵=(3,4) de la figura dada.

a. Métrica Euclidiana.

b. Métrica Manhattan.

c. Métrica Chebyshev

d. Métrica Minkowski de orden 𝑝 = 0.7

In [4]:
def euclidean(a, b):
    return math.sqrt((b[0] - a[0])**2 + (b[1] - a[1])**2)

def manhattan(a, b):
    return abs(b[0] - a[0]) + abs(b[1] - a[1])

def chevysheb(a, b):
    return max((abs(b[0] - a[0]), abs(b[1] - a[1])))

def minkowski(a, b, p):
    return abs(b[0] - a[0])**p + abs(b[1] - a[1])**p
    

a = (2, 1)
b = (3, 4)
p = 0.7
print("A:", a)
print("B:", b)
print("Euclidean distance: ", euclidean(a, b))
print("Manhattan distance: ", manhattan(a, b))
print("Chevysheb distance: ", chevysheb(a, b))
print("Minkowski distance with p=%f: " % p, minkowski(a, b, p))

A: (2, 1)
B: (3, 4)
Euclidean distance:  3.1622776601683795
Manhattan distance:  4
Chevysheb distance:  3
Minkowski distance with p=0.700000:  3.157669279974593


3. El concepto de “separabilidad” de un kernel significa que en ocasiones un kernel de tamaño 𝑚 × 𝑚 puede separarse (o factorizarse) en dos kernels de tamaño 1 × 𝑚, reduciendo la complejidad del proceso. Consideremos el kernel bidimensional 𝑄3x3 = [[1, −3, 1], [−3, 9, −3], [1, −3, 1]], y el kernel unidimensional 𝑞 = [−1, 3, −1].

a. Muestra que 𝑄 = 𝑞𝑇𝑞, donde 𝑇 indica la traspuesta y se está considerando el producto usual de matrices. Es decir, se está mostrando que 𝑄 es “separable”.

b. Usando la imagen 𝐻 de tamaño 4 × 4 dada a continuación y el criterio de simetría (padding), obtener cada una de las convoluciones indicadas, es decir, muestra que 𝐻 puede convolucionarse con un kernel bidimensional, o bien,  convolucionarlo con dos unidimensionales, y el resultado es el mismo:

c. 𝐻 ∗ 𝑄

d. 𝐻 ∗ 𝑞

e. (𝐻 ∗ 𝑞) ∗ 𝑞

Imagen 𝐻:

|    |    |    |    |
|----|----|----|----|
| 10 | 20 | 0  | 30 |
| 20 | 0  | 10 | 20 |
| 10 | 0  | 40 | 0  |
| 15 | 40 | 0  | 30 |

In [5]:
Q = np.array([[1, -3, 1], [-3, 9, -3], [1, -3, 1]])
print("Q:\n", Q, "\n")

q = np.array([[-1, 3, -1]])
print("q:\n", q, "\n")

qt = q.transpose()
print("qT:\n", qt, "\n")

qtq = np.dot(qt, q)
print("qTq:\n", qtq, "\n")

print("Comparison between Q and qtq:\n", qtq == Q)

Q:
 [[ 1 -3  1]
 [-3  9 -3]
 [ 1 -3  1]] 

q:
 [[-1  3 -1]] 

qT:
 [[-1]
 [ 3]
 [-1]] 

qTq:
 [[ 1 -3  1]
 [-3  9 -3]
 [ 1 -3  1]] 

Comparison between Q and qtq:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
def cross_correlation(image, kernel, convolution=False, padding="zeroes"):
    image_row, image_col = image.shape
    kernel_row, kernel_col = kernel.shape

    output = np.zeros(image.shape)

    pad_height = int((kernel_row - 1) / 2)
    pad_width = int((kernel_col - 1) / 2)
    
    padded_image = image
    
    if padding:
        padded_image = np.zeros((image_row + (2 * pad_height), image_col + (2 * pad_width)))
        padded_image[pad_height:padded_image.shape[0] - pad_height, pad_width:padded_image.shape[1] - pad_width] = image
        if padding == "replica":
            if pad_height:
                padded_image[0:pad_height, :] = padded_image[pad_height:pad_height+1, :]
                padded_image[-pad_height:, :] = padded_image[-pad_height-1:-pad_height, :]
            if pad_width:
                padded_image[:, 0:pad_width] = padded_image[:, pad_width:pad_width+1]
                padded_image[:, -pad_width:] = padded_image[:, -pad_width-1:-pad_width]
        elif padding == "symmetry":
            if pad_height:
                padded_image[0:pad_height, :] = np.flip(padded_image[pad_height:pad_height*2, :], axis=0)
                padded_image[-pad_height:, :] = np.flip(padded_image[-pad_height*2:-pad_height, :], axis=0)
            if pad_width:
                padded_image[:, 0:pad_width] = np.flip(padded_image[:, pad_width:pad_width*2], axis=1)
                padded_image[:, -pad_width:] = np.flip(padded_image[:, -pad_width*2:-pad_width], axis=1)
        elif padding == "cyclic":
            if pad_height:
                padded_image[0:pad_height, :] = padded_image[-pad_height*2:-pad_height, :]
                padded_image[-pad_height:, :] = padded_image[pad_height:pad_height*2, :]
            if pad_width:
                padded_image[:, 0:pad_width] = padded_image[:, -pad_width*2:-pad_width]
                padded_image[:, -pad_width:] = padded_image[:, pad_width:pad_width*2]

    if convolution:
        kernel = np.rot90(kernel, 2)

    for row in range(image_row):
        for col in range(image_col):
            output[row, col] = np.sum(kernel * padded_image[row:row + kernel_row, col:col + kernel_col])
    return output


H = np.array([
    [10, 20, 0, 30],
    [20, 0, 10, 20],
    [10, 0, 40, 0],
    [15, 40, 0, 30]
])
print("𝐻:\n", H, "\n")

HxQ = cross_correlation(H, Q, convolution=True, padding="symmetry")
print("𝐻 ∗ 𝑄:\n", HxQ, "\n")

Hxq = cross_correlation(H, q, convolution=True, padding="symmetry")
print("𝐻 ∗ 𝑞:\n", Hxq, "\n")

Hxqxqt = cross_correlation(Hxq, qt, convolution=True, padding="symmetry")
print("(𝐻 ∗ 𝑞) ∗ 𝑞T:\n", Hxqxqt, "\n")

𝐻:
 [[10 20  0 30]
 [20  0 10 20]
 [10  0 40  0]
 [15 40  0 30]] 

𝐻 ∗ 𝑄:
 [[ -40.  130. -110.   90.]
 [ 100.  -90.  -40.   70.]
 [  30. -225.  420. -210.]
 [ -40.  260. -260.  160.]] 

𝐻 ∗ 𝑞:
 [[  0.  50. -50.  60.]
 [ 40. -30.  10.  30.]
 [ 20. -50. 120. -40.]
 [-10. 105. -70.  60.]] 

(𝐻 ∗ 𝑞) ∗ 𝑞T:
 [[ -40.  130. -110.   90.]
 [ 100.  -90.  -40.   70.]
 [  30. -225.  420. -210.]
 [ -40.  260. -260.  160.]] 



4. Mediante las fórmulas correspondientes vistas en clase y a partir de la imagen 𝐼 mostrada más abajo (se muestran solamente las columnas 15, 16, 17 y los renglones 6, 7 ,8), interpolar el valor 𝐼(15.85, 7.40), usando:

a. Interpolación mediante el vecino más cercano.

b. Interpolación bilineal.

| | | |
|-----|-----|----|
| 110 | 125 | 98 |
| 106 | 120 | 95 |
| 100 | 110 | 90 |

In [7]:
def nn_interpolation(image, x0, y0):
    return image[round(x0)][round(y0)]

def bl_interpolation(image, x0, y0):
    u, a = math.modf(x0)
    v, b = math.modf(y0)
    a = int(a)
    b = int(b)
    i = 0
    i += image[a][b] * (1 - u) * (1 - v)
    i += image[a+1][b] * u * (1 - v)
    i += image[a][b+1] * (1 - u) * v
    i += image[a+1][b+1] * u * v
    return i

I = np.array([
    [110, 125, 98],
    [106, 120, 95],
    [100, 110, 90]
])
print("Image[15:18, 6:9]:\n", I, "\n")

print("Nearest Neighbor Interpolation of (15.85, 7.40):", nn_interpolation(I, 15.85-15, 7.40-6))
print("Bilinear Interpolation of (15.85, 7.40):", bl_interpolation(I, 15.85-15, 7.40-6))

Image[15:18, 6:9]:
 [[110 125  98]
 [106 120  95]
 [100 110  90]] 

Nearest Neighbor Interpolation of (15.85, 7.40): 120
Bilinear Interpolation of (15.85, 7.40): 110.63


5. Responde a cada uno de los incisos siguientes, con la imagen 𝐴 de tamaño 3 × 4 dada, y donde los valores de la imagen varían en 4-bits de niveles de gris.

| | | | |
|----|----|---|----|
| 8  | 10 | 7 | 7  |
| 15 | 3  | 5 | 9  |
| 13 | 2  | 0 | 12 |

a. Aplicar a dicha imagen la siguiente transformación de umbralado: 𝑇(𝑥) = 15 𝑠𝑖 𝑥 ≤ 6, 𝑜 𝑏𝑖𝑒𝑛, 𝑥 ≥ 13 | 15 − 𝑥 𝑠𝑖 𝑜𝑡𝑟𝑜 𝑐𝑎𝑠𝑜

b. Aplicar a la imagen 𝐴 una transformación de vecindad mediante la convolución definida por el kernel 3 × 3: [[-1, -1, 0], [-1, 0, 1], [0, 1, 1]] Utilizar el criterio cíclico de rellenado de bordes.

c. Aplicar a la imagen resultante del inciso (b) anterior una transformación de escalamiento para que los valores de gris queden de nuevo en el intervalo [0, 15].

d. Utilizando el criterio de réplica para el rellenado de bordes, aplicar a la imagen 𝐴 una correlación cruzada usando los kernels: 𝐷𝑥: [[-1  0  1]], 𝐷𝑦: [[-1], [ 0], [ 1]] , para obtener las siguientes 3 imágenes: (a) la imagen de la derivada parcial con 𝐷𝑥; (b) la de la derivada parcial con 𝐷𝑦; (c) la del gradiente aproximado con |∇𝑓| ≈ |𝐷𝑥| + |𝐷𝑦|.

e. Aplicar el operador Mediana 3 × 3 a la imagen 𝐴 usando el criterio de rellenado de los bordes con ceros. 

In [8]:
A = np.array([
    [8, 10, 7, 7],
    [15, 3, 5, 9],
    [13, 2, 0, 12]
])
print("A:\n", A, "\n")

Ap = np.zeros(A.shape)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if A[i][j] <= 6 or A[i][j] >= 13:
            Ap[i][j] = 15
        else:
            Ap[i][j] = 15 - A[i][j]

print("Thresholded A:\n", Ap, "\n")

k = np.array([
    [-1, -1, 0],
    [-1, 0, 1],
    [0, 1, 1]
])
print("k:\n", k, "\n")

Axk = cross_correlation(A, k, padding="cyclic")
print("A ∗ k:\n", Axk, "\n")

def scale_matrix(matrix, a=0, b=1):
    result = np.zeros(A.shape)
    _min = np.amin(matrix)
    _max = np.amax(matrix)
    _range = _max - _min
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i][j] = round(a + ((matrix[i][j] - _min) * (b - a))/_range)
    return result

print("A ∗ k scaled:\n", scale_matrix(Axk, 0, 15), "\n")

dx = np.array([[-1, 0, 1]])
dy = dx.transpose()

print("𝐷𝑥:\n", dx, "\n")
print("𝐷𝑦:\n", dy, "\n")

Axdx = cross_correlation(A, dx, padding="replica")
print("A ∗ 𝐷𝑥:\n", Axdx, "\n")

Axdy = cross_correlation(A, dy, padding="replica")
print("A ∗ 𝐷𝑦:\n", Axdy, "\n")

df = np.zeros(A.shape)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        df[i][j] = abs(Axdx[i][j]) + abs(Axdy[i][j])
print("Gradient values of |𝐷𝑥| + |𝐷𝑦|:\n", df, "\n")

padded_A = np.zeros((A.shape[0] + 2, A.shape[1] + 2))
padded_A[1:padded_A.shape[0] - 1, 1:padded_A.shape[1] - 1] = A
filtered_A = np.zeros(A.shape)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        filtered_A[i, j] = np.median(padded_A[i:i + 3, j:j + 3])
print("Median filter of A using a 3x3 mask:\n", filtered_A, "\n")

A:
 [[ 8 10  7  7]
 [15  3  5  9]
 [13  2  0 12]] 

Thresholded A:
 [[ 7.  5.  8.  8.]
 [15. 15. 15.  6.]
 [15. 15. 15.  3.]] 

k:
 [[-1 -1  0]
 [-1  0  1]
 [ 0  1  1]] 

A ∗ k:
 [[ -4.  -8.   9.  13.]
 [ -6. -26.   1.  21.]
 [-16. -14.  16.  14.]] 

A ∗ k scaled:
 [[ 7.  6. 11. 12.]
 [ 6.  0.  9. 15.]
 [ 3.  4. 13. 13.]] 

𝐷𝑥:
 [[-1  0  1]] 

𝐷𝑦:
 [[-1]
 [ 0]
 [ 1]] 

A ∗ 𝐷𝑥:
 [[  2.  -1.  -3.   0.]
 [-12. -10.   6.   4.]
 [-11. -13.  10.  12.]] 

A ∗ 𝐷𝑦:
 [[ 7. -7. -2.  2.]
 [ 5. -8. -7.  5.]
 [-2. -1. -5.  3.]] 

Gradient values of |𝐷𝑥| + |𝐷𝑦|:
 [[ 9.  8.  5.  2.]
 [17. 18. 13.  9.]
 [13. 14. 15. 15.]] 

Median filter of A using a 3x3 mask:
 [[0. 5. 5. 0.]
 [3. 7. 7. 5.]
 [0. 2. 2. 0.]] 



6. Aplicar una ecualización uniforme a la imagen de 3-bits en niveles de grises
dada. Utilizar la función acumulada uniforme y la función piso para
redondear.

| | | | |
|---|---|---|---|
| 6 | 6 | 7 | 5 |
| 6 | 7 | 5 | 4 |
| 6 | 5 | 3 | 4 |
| 7 | 5 | 4 | 3 |

In [9]:
def equalize(matrix, bits):
    result = np.zeros(matrix.shape)
    new_values = {}
    nm = matrix.shape[0] * matrix.shape[1]
    acc = 0
    for g in range(bits):
        ng = np.count_nonzero(matrix == g)
        acc += ng/nm
        new_values[g] = math.floor(acc * bits)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i][j] = new_values[matrix[i][j]]
    return result
            

image = np.array([
    [6, 6, 7, 5],
    [6, 7, 5, 4],
    [6, 5, 3, 4],
    [7, 5, 4, 3]
])

equilized = equalize(image, 8)

print("Image:\n", image, "\n")
print("Equilized image:\n", equilized, "\n")

Image:
 [[6 6 7 5]
 [6 7 5 4]
 [6 5 3 4]
 [7 5 4 3]] 

Equilized image:
 [[6. 6. 8. 4.]
 [6. 8. 4. 2.]
 [6. 4. 1. 2.]
 [8. 4. 2. 1.]] 



7. A partir de la matriz A = [[4, 1], [1, 2]], obtener:

a. Traza y determinante.

Determinante = (4 x 2) + (1 * 1) = __7__

Traza = 4 + 2 = __6__


b. Eigenvalores.

Polinomio caracteristico = (-λ+4) * (-λ+2) + (1 * 1) = λ^2 - 6λ + 7

λ1 = (-(-6) - √(-6^2 - 4(7))) / 2

λ1 = (6 - √(36-28)) / 2

λ1 = 3 - √8 / 2

λ1 = 3 - √((2^2) * 2) / 2

λ1 = 3 - 2√2 / 2

λ1 = __3 - √2__

λ2 = __3 + √2__

c. Eigenvectores.

Para λ1 = 3 - √2:

[[1+√2, 1], [1, -1+√2]] * [[x], [y]]

(1+√2)x + y = 0

y = (-1-√2)x

__[[1], [-1-√2]]__


Para λ2 = 3 + √2:

[[1-√2, 1], [1, -1-√2]] * [[x], [y]]

x + (-1-√2)y = 0

x = (1+√2)y

__[[1+√2], [1]]__