# Gabriel Briones Sayeg A01222517

In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import numpy as np
from pandas import read_csv
from sklearn.utils import shuffle

In [3]:
iris = read_csv('iris_shorted.csv')
iris = shuffle(iris.values)
data = iris[:,:5]
labels = iris[:,5]

FileNotFoundError: [Errno 2] File b'iris_shorted.csv' does not exist: b'iris_shorted.csv'

## Iter 1

In [28]:
train_data = data[6:]
train_labels = labels[6:]
test_data = data[0:6]
test_labels = labels[0:6]

In [29]:
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(train_data,train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [30]:
predicted = knn.predict(test_data)

In [35]:
confusion_matrix(predicted, test_labels)

array([[4, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Iter 2

In [37]:
train_data = np.concatenate((data[0:6], data[12:]), axis=0)
train_labels = np.concatenate((labels[0:6], labels[12:]), axis=0)
test_data = data[6:12]
test_labels = labels[6:12]

In [38]:
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(train_data,train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [39]:
predicted = knn.predict(test_data)

In [40]:
confusion_matrix(predicted, test_labels)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Iter 3

In [41]:
train_data = np.concatenate((data[0:12], data[18:]), axis=0)
train_labels = np.concatenate((labels[0:12], labels[18:]), axis=0)
test_data = data[12:18]
test_labels = labels[12:18]

In [42]:
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(train_data,train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [43]:
predicted = knn.predict(test_data)

In [44]:
confusion_matrix(predicted, test_labels)

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 1]])

## Iter 4

In [45]:
train_data = np.concatenate((data[0:18], data[24:]), axis=0)
train_labels = np.concatenate((labels[0:18], labels[24:]), axis=0)
test_data = data[18:24]
test_labels = labels[18:24]

In [46]:
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(train_data,train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [47]:
predicted = knn.predict(test_data)

In [48]:
confusion_matrix(predicted, test_labels)

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

## Iter 5

In [49]:
train_data = data[:24]
train_labels = labels[:24]
test_data = data[24:]
test_labels = labels[24:]

In [50]:
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
knn.fit(train_data,train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [51]:
predicted = knn.predict(test_data)

In [52]:
confusion_matrix(predicted, test_labels)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 1, 2]])